name: agriplant
description: Agriculture plant app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  google_fonts: ^5.1.0
  badges: ^3.1.1
  timelines: ^0.1.0
  easy_stepper: ^0.7.3
  image_picker: ^0.8.5+3
  camera: ^0.10.5+9
  video_player: ^2.8.6
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  latlng: ^2.0.7
  permission_handler: ^11.3.1
  geolocator: ^11.0.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  flutter_tflite: ^1.0.1
  url_launcher: ^6.2.6
  youtube_player_flutter: ^9.0.1
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/services/
    - shorebird.yaml
